### ISSUE TITLE
Addition of UX Design

### ISSUE THREAD

**Issue by sudip-padhye** [airavata-courses/PingIntelligence#1]
This would provide an anticipated view of the User Interface that provides a good understanding of the look & feel of the app. Also, it should contain screen transitions from one screen to another with user commands/inputs.

**Comment by sudip-padhye** [comment]
UX Design provides a visual articulation of the solution, validation of ideas and concepts, test with users. This should be added to the GitHub repository's Wiki section.

**Comment by SrikanthVelpuri** [comment]
Uploading signup and signin pages.Both of them are designed in Adobe XD and I will upload Adobe XD files as .zip 
![sign up page](https://user-images.githubusercontent.com/19996897/107123690-ebfe4b80-686c-11eb-94a5-f1670792d8b2.JPG)
![signin page](https://user-images.githubusercontent.com/19996897/107123691-ec96e200-686c-11eb-8b4f-3ace915a0c2b.JPG)

**Comment by SrikanthVelpuri** [comment]
uploading sign up page removing all different components as a whole webpage image
![sign up page](https://user-images.githubusercontent.com/19996897/107123746-439cb700-686d-11eb-969f-aeaca0f7e800.JPG)

**Comment by SrikanthVelpuri** [comment]
browsing page
![Browsingphotos page](https://user-images.githubusercontent.com/19996897/107154482-1f120f00-6941-11eb-94c6-2252510b244a.JPG)

**Comment by SrikanthVelpuri** [comment]
Upload page
![upload page](https://user-images.githubusercontent.com/19996897/107154492-2a653a80-6941-11eb-9742-a48a8a98caec.JPG)
