### ISSUE TITLE
Need for the Information Architecture

### ISSUE THREAD

**Issue by sudip-padhye** [airavata-courses/PingIntelligence#3]
This diagram would organize different components of the system and provides various communication between each of them. Shortly, these are flow charts (Sketching, Wireframes, Journey Mapping, etc.). This diagram should be added to the README once completed.

**Comment by sudip-padhye** [comment]
@meetdvalia I have uploaded the Architecture Diagram as per our last discussion. Can you check it once before merging into the main branch?

**Comment by meetdvalia** [comment]
@sudip-padhye  can you add the description of which services are calling which other services and which all micro services that will be using databases

**Comment by sudip-padhye** [comment]
@meetdvalia Thanks for reviewing the PR. I will implement the suggested details and update the PR.

**Comment by sudip-padhye** [comment]
Closing this issue since the corresponding updates have been made & pull request has been merged.
