### ISSUE TITLE
Blue-Green Deployment Setup

### ISSUE THREAD

**Issue by sudip-padhye** [airavata-courses/PingIntelligence#59]
Need to figure how this can be achieved by maintaining the states (DB and Kafka messages).

**Comment by sudip-padhye** [comment]
Assigning the DB state maintenance task to @danagar0312. Anybody else wants to pitch in and provide any helpful insights? @SrikanthVelpuri @meetdvalia

**Comment by SrikanthVelpuri** [comment]
Using HAproxy Server for managing TACC and IU VMs for blue-green deployments. This solved our issue

**Comment by sudip-padhye** [comment]
Testing is done succesfully. Working as per requirement
